version: "3.4"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
      # Mount the local gcloud sdk configuration when developing. Note that this
      # will modify the contents on the host.
      - ${CLOUDSDK_CONFIG}/:/tmp/.config/gcloud
      # Avoid aliasing node_modules from the host directory
      - /app/node_modules
    environment:
      - CLOUDSDK_CONFIG=/tmp/.config/gcloud
      - CLOUDSDK_CORE_PROJECT
    command:
      bash -c "scripts/scrape.sh && scripts/deploy-data.sh &&
      scripts/deploy-site.sh"
