version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      # check 2 hours before Airflow deploys
      time: "22:00"
  - package-ecosystem: pip
      directory: /
      schedule:
        interval: daily
      reviewers:
        - BenWu
